chore: code refactoring
devtron-labs/git-sensor pull request #93
Opened 2024-03-04 07:49 UTC by ShashwatDadhich

code rafactoring for changes since and get location

2024-03-12 11:02 UTC, prakash100198 approved these changes
LGTM

2024-03-12 11:19 UTC, prakash100198 requested changes

2024-03-12 11:19 UTC, prakash100198 commented on pkg/git/RepositoryManager.go
>  	GetLocationForMaterial(material *sql.GitMaterial, cloningMode string) (location string, httpMatched bool, shMatched bool, err error)
We can change this name to GetCheckoutLocationFromGitUrl

2024-03-12 11:23 UTC, prakash100198 approved these changes

2024-03-14 11:43 UTC, kripanshdevtron approved these changes

2024-03-14 12:53 UTC, merged